#!/usr/bin/env python3
"""Derives the web app's icons from the Android ones, so the two cannot drift.

Android vector drawables already hold SVG path data, so the instrument icons
convert exactly rather than being redrawn. Run this after changing anything in
app/src/main/res/drawable or docs/play-assets; the output is committed.

    tools/generate-web-assets.py

Needs Pillow and rsvg-convert.
"""

from __future__ import annotations

import pathlib
import re
import subprocess
import sys
import xml.etree.ElementTree as ElementTree

ROOT = pathlib.Path(__file__).resolve().parent.parent
DRAWABLE = ROOT / "app/src/main/res/drawable"
WEB = ROOT / "web"
ICONS = WEB / "icons"
ANDROID_NS = "{http://schemas.android.com/apk/res/android}"

# Matches io.github.deeplow.nobstuner.ui.components.InstrumentIcons.
FAMILY_ICONS = {
    "GUITAR": "ic_instrument_guitar",
    "BASS": "ic_instrument_bass",
    "UKULELE": "ic_instrument_ukulele",
    "BANJO": "ic_instrument_banjo",
    "MANDOLIN": "ic_instrument_mandolin",
    "ORCHESTRAL": "ic_instrument_orchestral",
    "OTHER": "ic_instrument_other",
}


def read_paths(name: str) -> tuple[float, list[tuple[str, str | None]]]:
    """Returns a drawable's viewport size and its (pathData, fillType) pairs."""
    root = ElementTree.parse(DRAWABLE / f"{name}.xml").getroot()
    viewport = float(root.get(f"{ANDROID_NS}viewportWidth"))
    paths = [
        (element.get(f"{ANDROID_NS}pathData"), element.get(f"{ANDROID_NS}fillType"))
        for element in root.iter("path")
    ]
    return viewport, paths


def svg_body(name: str, fill: str | None = None) -> tuple[float, str]:
    viewport, paths = read_paths(name)
    markup = []
    for data, fill_type in paths:
        attributes = [f'd="{data}"']
        if fill_type and fill_type.lower() == "evenodd":
            attributes.append('fill-rule="evenodd"')
        if fill:
            attributes.append(f'fill="{fill}"')
        markup.append("<path " + " ".join(attributes) + "/>")
    return viewport, "".join(markup)


def write_instrument_icons() -> None:
    """One ES module holding every instrument glyph, inline to save requests."""
    entries = []
    for family, drawable in FAMILY_ICONS.items():
        viewport, body = svg_body(drawable)
        entries.append(f'  {family}: \'<svg viewBox="0 0 {viewport:g} {viewport:g}" '
                       f'aria-hidden="true" focusable="false">{body}</svg>\',')
    module = (
        "// Generated by tools/generate-web-assets.py from the Android vector\n"
        "// drawables in app/src/main/res/drawable. Do not edit by hand.\n"
        "//\n"
        "// `currentColor` is inherited, so each glyph takes the colour of the\n"
        "// element it sits in, the way the Compose `tint` does.\n"
        "export const INSTRUMENT_ICONS = {\n"
        + "\n".join(entries)
        + "\n};\n\n"
        "/** Chromatic mode belongs to no instrument in particular. */\n"
        "export const CHROMATIC_ICON = INSTRUMENT_ICONS.OTHER;\n"
    )
    (WEB / "src/instrument-icons.js").write_text(module)
    print("wrote web/src/instrument-icons.js")


def launcher_svg() -> str:
    background = re.search(
        r'name="ic_launcher_background">(#[0-9A-Fa-f]{6})<',
        (ROOT / "app/src/main/res/values/ic_launcher_background.xml").read_text(),
    ).group(1)
    viewport, body = svg_body("ic_launcher_foreground")
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {viewport:g} {viewport:g}">'
        f'<rect width="{viewport:g}" height="{viewport:g}" fill="{background}"/>'
        f"{body}</svg>"
    )


def write_icons() -> None:
    from PIL import Image

    ICONS.mkdir(parents=True, exist_ok=True)

    # The maskable icon is the adaptive icon rendered whole: the fork already
    # sits inside the central 66% that a launcher may crop to.
    svg = launcher_svg()
    (ICONS / "icon.svg").write_text(svg)
    subprocess.run(
        ["rsvg-convert", "-w", "512", "-h", "512", "-o", str(ICONS / "maskable-512.png")],
        input=svg.encode(), check=True,
    )
    print("wrote web/icons/icon.svg, maskable-512.png")

    # The square icon is the one already on the Play listing.
    source = Image.open(ROOT / "docs/play-assets/play-icon-512.png").convert("RGB")
    for size in (192, 512):
        source.resize((size, size), Image.LANCZOS).save(ICONS / f"icon-{size}.png")
        print(f"wrote web/icons/icon-{size}.png")
    # iOS ignores the manifest and wants its own, opaque, un-rounded.
    source.resize((180, 180), Image.LANCZOS).save(ICONS / "apple-touch-icon.png")
    print("wrote web/icons/apple-touch-icon.png")


def main() -> int:
    if not DRAWABLE.is_dir():
        print(f"no drawables at {DRAWABLE}", file=sys.stderr)
        return 1
    write_instrument_icons()
    write_icons()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
